export type ActionExplanationCode =
  | 'DECISION_REDUCE_CHOICES'
  | 'DECISION_HIDE_LOW_CONFIDENCE_SLOTS'
  | 'DECISION_ESCALATE_TO_HUMAN'
  | 'FUNNEL_CONCIERGE_PATH_EMPHASIZED'
  | 'FUNNEL_COMPACT_LAYOUT'
  | 'QUOTE_LATENCY_HIGH'
  | 'DEGRADED_RUNTIME'
  | 'QUOTE_FAILURE_RECOVERY';
