
// SANTIS GALLERY MANAGER
// Generated by Control Center
// v2.0 (Singularity Era)

window.GALLERY_DATA = [
    {
        "file": "santis_card_hammam_v1.png",
        "category": "hamam",
        "caption": "Geleneksel Türk Hamamı",
        "mood": "mystic"
    },
    {
        "file": "santis_card_couple_v1.png",
        "category": "massage",
        "caption": "Çift Masajı (Couple Suite)",
        "mood": "romantic"
    },
    {
        "file": "santis_card_skincare_v1.png",
        "category": "skincare",
        "caption": "Sothys Cilt Bakımı",
        "mood": "clean"
    },
    {
        "file": "hero-general.webp",
        "category": "ambiance",
        "caption": "Santis Lounge & Relax",
        "mood": "calm"
    },
    {
        "file": "neurova-face-mask-4x5-1080x1350.webp",
        "category": "skincare",
        "caption": "Premium Yüz Maskeleri",
        "mood": "energetic"
    },
    {
        "file": "Hammamda köpük masajı huzuru.webp",
        "category": "hamam",
        "caption": "Köpük Masajı Ritüeli",
        "mood": "relax"
    },
    {
        "file": "Altın yağı ve ellerin zarafeti.webp",
        "category": "massage",
        "caption": "Altın Yağı Terapisi",
        "mood": "luxury"
    },
    {
        "file": "Anjali Mudra with soft lighting.webp",
        "category": "yoga",
        "caption": "Namaste & Denge",
        "mood": "spiritual"
    },
    {
        "file": "Şirodhara terapi anı.webp",
        "category": "massage",
        "caption": "Şirodhara Baş Terapisi",
        "mood": "deep"
    },
    {
        "file": "neurova_cellulite_yatay_3x2_quietlux.webp",
        "category": "skincare",
        "caption": "Selülit Tedavisi",
        "mood": "clinical"
    }
];
