// SANTIS CLUB - SERVICES DATABASE
// Generated by Control Center

// HAMMAM
const NV_HAMMAM = [
    {
        "id": "h1",
        "category": "hammam",
        "title": "Geleneksel Hamam Ritüeli",
        "desc": "Kese ve köpük ritüeli ile geleneksel arınma, Osmanlı zarafetiyle yenilenme.",
        "duration": "60 dk",
        "price": "110 €",
        "tier": "CLASSIC",
        "img": "assets/img/cards/santis_card_hammam_v1.webp",
        "isSpecial": false
    },
    {
        "id": "h2",
        "category": "hammam",
        "title": "Köpük Masajı (Hamam)",
        "desc": "Geleneksel köpükle rahatlatıcı masaj, kasları gevşeten sıcak dokunuşlar.",
        "duration": "45 dk",
        "price": "85 €",
        "tier": "PREMIUM",
        "img": "assets/img/cards/santis_card_hammam_v1.webp",
        "isSpecial": true
    },
    {
        "id": "h-ai-test",
        "category": "hammam",
        "title": "AI Test Ritüeli (Otomasyon)",
        "desc": "Yapay Zeka tarafından başarıyla eklenen test verisidir. Sistem otomasyonunun çalıştığını doğrular.",
        "duration": "10 dk",
        "price": "Ücretsiz",
        "tier": "PREMIUM",
        "img": "assets/img/cards/santis_card_hammam_v1.webp",
        "isSpecial": true
    }
];

// DATA: LABELS
const NV_HAMMAM_CATEGORY_LABELS = { "hammam": "Hamam Ritüelleri" };
const NV_HAMMAM_CATEGORY_ORDER = ["hammam"];


// MASSAGES
const NV_MASSAGES = [
    {
        "id": "m1",
        "category": "classicMassages",
        "title": "Klasik İsveç Masajı",
        "desc": "Orta şiddetli, tüm vücut rahatlama masajı.",
        "duration": "50 dk",
        "price": "85 €",
        "tier": "CLASSIC",
        "img": "card-massage-1.jpg",
        "isSpecial": false
    },
    {
        "id": "m2",
        "category": "asianMassages",
        "title": "Bali Masajı",
        "desc": "Aromatik yağlar ve germe hareketleriyle yapılan geleneksel Bali masajı.",
        "duration": "50 dk",
        "price": "95 €",
        "tier": "PREMIUM",
        "img": "card-massage-2.jpg",
        "isSpecial": false
    }
];

const NV_MASSAGES_CATEGORY_LABELS = {
    "classicMassages": "Klasik Masajlar",
    "asianMassages": "Uzak Doğu",
    "sportsTherapy": "Spor & Terapi",
    "signatureCouples": "İmza & Çift"
};
const NV_MASSAGES_CATEGORY_ORDER = ["classicMassages", "asianMassages", "sportsTherapy", "signatureCouples"];


// SKINCARE
const NV_SKINCARE = [
    {
        "id": "s1",
        "category": "faceSothys",
        "title": "Klasik Cilt Bakımı",
        "desc": "Derinlemesine temizlik ve nemlendirme.",
        "duration": "45 dk",
        "price": "80 €",
        "tier": "BASIC",
        "img": "card-face-1.jpg",
        "isSpecial": false
    }
];

const NV_SKINCARE_CATEGORY_LABELS = { "faceSothys": "Sothys Yüz Bakımları" };
const NV_SKINCARE_CATEGORY_ORDER = ["faceSothys"];
