// SANTIS SOCIAL MANAGER - DATA CORE
// Generated by Control Center at 01.02.2026 15:30:00
// v1.0 (Initial)

const SOCIAL_DATA = {
    "platforms": {
        "instagram": { "id": "instagram", "title": "Instagram", "url": "", "icon": "fab fa-instagram", "active": true },
        "facebook": { "id": "facebook", "title": "Facebook", "url": "", "icon": "fab fa-facebook", "active": false },
        "whatsapp": { "id": "whatsapp", "title": "WhatsApp", "url": "", "icon": "fab fa-whatsapp", "active": true },
        "linkedin": { "id": "linkedin", "title": "LinkedIn", "url": "", "icon": "fab fa-linkedin", "active": false },
        "youtube": { "id": "youtube", "title": "YouTube", "url": "", "icon": "fab fa-youtube", "active": false },
        "twitter": { "id": "twitter", "title": "X (Twitter)", "url": "", "icon": "fab fa-x-twitter", "active": false }
    },
    "biolinks": [
        { "title": "Randevu Al (Online)", "url": "/booking.html", "urgent": true, "clickCount": 0 },
        { "title": "Konum & Ulaşım", "url": "https://maps.google.com/...", "urgent": false, "clickCount": 0 }
    ],
    "concierge": {
        "active": false,
        "video": ""
    },
    "posts": [
        { "id": 1, "title": "Sevgililer Günü Özel", "date": "16 Şubat", "type": "Post", "status": "ready", "img": "love_spa.jpg" },
        { "id": 2, "title": "Hamam Ritüeli", "date": "20 Şubat", "type": "Story", "status": "draft", "img": "hammam_steam.jpg" },
        { "id": 3, "title": "Hafta Sonu İndirimi", "date": "22 Şubat (Tahmini)", "type": "Post", "status": "draft", "img": "discount.jpg" }
    ]
};
