// SANTIS GALLERY MANAGER
// Generated by Control Center
// v2.0 (Singularity Era)

const GALLERY_DATA = [
    {
        "file": "santis_card_hammam_v1.png",
        "category": "hamam",
        "caption": "Geleneksel Türk Hamamı",
        "mood": "mystic",
        "audio": "water_steam.mp3"
    },
    {
        "file": "santis_card_couple_v1.png",
        "category": "massage",
        "caption": "Çift Masajı (Couple Suite)",
        "mood": "romantic",
        "audio": "soft_piano.mp3"
    },
    {
        "file": "santis_card_skincare_v1.png",
        "category": "skincare",
        "caption": "Sothys Cilt Bakımı",
        "mood": "clean",
        "audio": "silence.mp3"
    },
    {
        "file": "hero-general.webp",
        "category": "ambiance",
        "caption": "Santis Lounge & Relax",
        "mood": "calm",
        "audio": "lounge_jazz.mp3"
    }
];
