
// SANTIS CLUB - PRODUCT CATALOG DATABASE
// Generated by Control Center at 01.02.2026 14:17:15

window.productCatalog = [
    {
        "id": 1,
        "name": "Secrets de Sothys® Cream",
        "cat": "face-youth",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "PRESTIGE",
        "desc": "Gençlik genlerini harekete geçiren lüks anti-aging bakım kremi. Sothys Gülü kök hücreleri ile formüle edilmiştir. Cildin biyolojik saatini yavaşlatır.",
        "benefit": "Kırışıklık görünümünü azaltır ve cildi sıkılaştırır.",
        "usage": "Sabah ve akşam temiz cilde uygulayın."
    },
    {
        "id": 2,
        "name": "Youth Serums Pack",
        "cat": "face-youth",
        "price": "Bilgi Al",
        "img": "product-oil.png",
        "badge": "SET",
        "desc": "Kırışıklık ve sıkılaşma karşıtı 6 farklı aktif serum kiti. Cildin ihtiyacına göre kombine edilebilir. Kişiselleştirilmiş gençlik bakımı.",
        "benefit": "Cildi yeniden yapılandırır ve toparlar.",
        "usage": "Serumları karıştırarak veya tek başına uygulayın."
    },
    {
        "id": 3,
        "name": "Hydra3Ha™ Intensive Serum",
        "cat": "face-hydra",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "BEST SELLER",
        "desc": "Cildin nem hafızasını canlandıran hyalüronik asit serumu. Anında dolgunluk etkisi sağlar ve nem bariyerini güçlendirir.",
        "benefit": "Derinlemesine nemlendirme ve dolgunlaştırma.",
        "usage": "Nemlendiriciden önce sabah/akşam uygulayın."
    },
    {
        "id": 4,
        "name": "Hydra3Ha™ Gel-Cream",
        "cat": "face-hydra",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "",
        "desc": "Normal ve karma ciltler için ferahlatıcı nemlendirici. Hafif dokusuyla hızla emilir ve cildi yumuşatır.",
        "benefit": "Hafif dokulu, uzun süreli nemlendirme.",
        "usage": "Temiz cilde günde iki kez uygulayın."
    },
    {
        "id": 5,
        "name": "Detox Energie™ Serum",
        "cat": "face-detox",
        "price": "Bilgi Al",
        "img": "product-oil.png",
        "badge": "NEW",
        "desc": "Hücresel enerjiyi artıran ve kirliliğe karşı koruyan serum. Cildi canlandırır, ışıltı verir ve çevresel faktörlere karşı kalkan oluşturur.",
        "benefit": "Cildi arındırır ve enerji verir.",
        "usage": "Detox kremi öncesinde uygulayın."
    },
    {
        "id": 6,
        "name": "Sothys Homme Cleanser",
        "cat": "face-men",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "",
        "desc": "Erkek cildi için 3'ü 1 arada temizleyici ve canlandırıcı. Yüz, vücut ve saç için uygundur. Enerji veren volkanik kaya özleri içerir.",
        "benefit": "Tek adımda temizlik ve canlılık.",
        "usage": "Her sabah duşta veya yüz yıkarken kullanın."
    },
    {
        "id": 7,
        "name": "Age-Defying Humectant",
        "cat": "face-men",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "",
        "desc": "Erkekler için yaşlanma karşıtı nemlendirici fluid. Hafif yapısıyla yağlı his bırakmaz, cildi rahatlatır.",
        "benefit": "Yaşlanma belirtilerini geciktirir.",
        "usage": "Tıraş sonrası veya sabah/akşam uygulayın."
    },
    {
        "id": 8,
        "name": "Slimming Activator",
        "cat": "body-slim",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "",
        "desc": "Selülit görünümünü azaltmaya yardımcı vücut serumu. Düzenli kullanımda incelme etkisi sağlar ve cilt dokusunu düzeltir.",
        "benefit": "Sıkılaşma ve portakal kabuğu görünümünde azalma.",
        "usage": "Sorunlu bölgelere masaj yaparak uygulayın."
    },
    {
        "id": 9,
        "name": "Hammam Scrub",
        "cat": "body-care",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "",
        "desc": "Geleneksel kese etkisi yaratan aromatik vücut peelingi. Ölü derileri nazikçe temizler ve cildi ipek gibi yapar.",
        "benefit": "Pürüzsüz ve yenilenmiş bir cilt.",
        "usage": "Haftada 1-2 kez duşta uygulayın."
    },
    {
        "id": 10,
        "name": "Self-Tanning Gel",
        "cat": "sun-care",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "SUMMER",
        "desc": "Güneşsiz, doğal ve eşit bronzluk sağlayan yüz/vücut jeli. İtalyan misafirlerin favorisi. Lekesiz ve doğal bir ton sağlar.",
        "benefit": "Güneşe çıkmadan doğal bronzluk.",
        "usage": "Eşit şekilde tüm vücuda yayın, elleri yıkayın."
    },
    {
        "id": 11,
        "name": "SPF30 Protective Oil",
        "cat": "sun-care",
        "price": "Bilgi Al",
        "img": "product-oil.png",
        "badge": "",
        "desc": "Saç ve vücut için koruyucu, besleyici kuru yağ. Suya dayanıklı formül. Tiare çiçeği kokusuyla yazı hissettirir.",
        "benefit": "UVA/UVB koruması ve saten bitiş.",
        "usage": "Güneşe çıkmadan önce cilde ve saça uygulayın."
    },
    {
        "id": 12,
        "name": "After-Sun Milk",
        "cat": "sun-care",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "",
        "desc": "Bronzluğu uzatan ve cildi yatıştıran bakım sütü. Güneş yanığı etkilerini hafifletir ve cildi besler.",
        "benefit": "Yatıştırma ve bronzluğu koruma.",
        "usage": "Güneş sonrası temiz cilde bolca uygulayın."
    },
    {
        "id": 13,
        "name": "Organic Radiance Mask",
        "cat": "organics",
        "price": "Bilgi Al",
        "img": "product-cream.png",
        "badge": "ECO-CERT",
        "desc": "Huş ağacı özlü organik ışıltı maskesi. Cildi derinlemesine nemlendirir ve canlandırır. %99 doğal içerik.",
        "benefit": "Doğal ışıltı ve nem.",
        "usage": "Haftada bir kez ince tabaka halinde uygulayın."
    },
    {
        "id": 14,
        "name": "Santis Signature Robe",
        "cat": "home-textile",
        "price": "Bilgi Al",
        "img": "hammam.png",
        "badge": "LUXURY",
        "desc": "%100 Pamuklu, özel dokuma premium spa bornozu. Otelimizdeki lüks deneyimi evinize taşıyın. Waffle dokusuyla hafiftir.",
        "benefit": "Spa konforunu evinizde yaşayın.",
        "usage": "Yıkama talimatına uygun temizleyin."
    },
    {
        "id": 15,
        "name": "Premium Havlu Seti",
        "cat": "home-textile",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "",
        "desc": "3'lü (El, Yüz, Banyo) ultra yumuşak havlu seti. Yüksek emiş gücü ve yumuşak doku. Santis Club nakışlı.",
        "benefit": "Yumuşaklık ve yüksek emicilik.",
        "usage": "İlk kullanımdan önce yıkayın."
    },
    {
        "id": 16,
        "name": "Relaxing Aroma Oil",
        "cat": "home-aroma",
        "price": "Bilgi Al",
        "img": "product-oil.png",
        "badge": "",
        "desc": "Santis'in imza kokusu: Lavanta ve Sandal ağacı. Difüzör ve buhurdanlık kullanımı için uygundur. Zihni sakinleştirir.",
        "benefit": "Ortamın havasını değiştirir, rahatlatır.",
        "usage": "Difüzöre 3-4 damla damlatın."
    },
    {
        "id": 17,
        "name": "Hediye Kartı (Gift Card)",
        "cat": "home-gift",
        "price": "Limit Seç",
        "img": "santis_card_products_v1.png",
        "badge": "",
        "desc": "Sevdiklerinize spa deneyimi hediye edin. Tuz Odası, Masaj veya Hamam ritüelleri için geçerlidir. 6 ay kullanım süresi.",
        "benefit": "Unutulmaz bir deneyim hediye edin.",
        "usage": "Resepsiyonda veya rezervasyonda kullanılır."
    },
    // SANTIS CLASSIC COLLECTION (Essential Therapies)
    // SANTIS CLASSIC COLLECTION (Essential Therapies)
    {
        "id": "classic-swedish",
        "name": "Classic Swedish Massage",
        "cat": "massage-classic",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "CLASSIC",
        "desc": "Batı'nın en eski ve temel masaj tekniği. Tüm vücuda uygulanan orta şiddetteki manipülasyonlarla kan dolaşımı hızlandırılır ve kaslar gevşetilir.",
        "benefit": "Genel rahatlama ve stres atımı.",
        "usage": "Doğal Yağlar ile"
    },
    {
        "id": "classic-aroma",
        "name": "Aromatherapy Massage",
        "cat": "massage-classic",
        "price": "Bilgi Al",
        "img": "santis_card_shirodhara_v1.png",
        "badge": "SOUL",
        "desc": "Bitkilerin özü, ruhun şifası. Kişinin ihtiyacına göre seçilen (Lavanta, Portakal, Biberiye) esansiyel yağlarla yapılan hafif ve ritmik bir masaj.",
        "benefit": "Zihinsel denge ve duygusal arınma.",
        "usage": "Kişiye Özel Esans Seçimi"
    },
    {
        "id": "classic-antistress",
        "name": "Anti-Stress Massage",
        "cat": "massage-classic",
        "price": "Bilgi Al",
        "img": "santis_card_reflexology_v1.png",
        "badge": "RELAX",
        "desc": "Günün yorgunluğunu atmak için boyun, omuz ve sırt bölgesine odaklanan yavaş ve ritmik bir terapi. Kas gerginliklerini çözer.",
        "benefit": "Bölgesel rahatlama (Baş, Boyun, Omuz).",
        "usage": "30 Dk veya 50 Dk Seçenek"
    },
    {
        "id": "classic-bronze",
        "name": "Bronze Massage (Cocoa)",
        "cat": "massage-classic",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "SUMMER",
        "desc": "Kakao ve Havuç yağı karışımıyla yapılan, bronzluğu hızlandıran ve sabitleyen özel bir yaz masajı. Cildi besler ve parlatır.",
        "benefit": "Altın rengi, kalıcı bronzluk.",
        "usage": "Güneşlenme öncesi/sonrası"
    },
    // ... (Thai items unchanged) ...

    // --- NEW: ANTI-CELLULITE RESEARCH ADDITIONS ---
    {
        "id": "detox-g5",
        "name": "G5 Vibro-Sculpting",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_deeptissue_v1.png",
        "badge": "MECHANICAL",
        "desc": "İnatçı selülitler için mekanik çözüm. Hızlı titreşimli başlık (G5) ile yağ blokları parçalanır ve kan dolaşımı maksimum seviyeye çıkarılır.",
        "benefit": "Selülit görünümünü azaltır, dokuyu pürüzsüzleştirir.",
        "usage": "Bölgesel Uygulama (Bacak/Basen)"
    },
    {
        "id": "detox-madero",
        "name": "Brazilian Maderotherapy",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "WOOD",
        "desc": "Kolombiya menşeli 'Ahşap Terapisi'. Anatomik şekilli tahta silindirlerle yapılan ritmik masaj, lenfatik sistemi uyarır ve vücudu şekillendirir.",
        "benefit": "Vücut kontürünü belirginleştirir (Body Contouring).",
        "usage": "%100 Doğal Ahşap Ekipmanlar"
    },
    {
        "id": "detox-coffee",
        "name": "Espresso Slimming Ritual",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "CAFFEINE",
        "desc": "Kafeinin lipolitik (yağ yakıcı) gücü. Yeşil kahve çekirdekleri ve acı biber özlü maske, metabolizmayı hızlandırarak incelmeyi destekler.",
        "benefit": "Metabolik hızlanma ve sıkılaşma.",
        "usage": "Peeling + Maske + Masaj"
    },
    {
        "id": "detox-cryo",
        "name": "Cryo-Toning Bandage",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "COLD",
        "desc": "Soğuk etkisiyle şok sıkılaşma. Mentol ve kofur içerikli soğuk bandajlar, vücut ısısını düşürerek kalorinin ısı üretimi için harcanmasını sağlar.",
        "benefit": "Ödem atar, bacakları hafifletir.",
        "usage": "20 Dk Bandaj Sarımı"
    },

    // PRESTIGE THAI COLLECTION
    {
        "id": "thai-royal",
        "name": "Royal Thai Massage",
        "cat": "massage-thai",
        "price": "Bilgi Al",
        "img": "santis_card_thai_v1.png",
        "badge": "ROYAL",
        "desc": "Tayland Sarayı'ndan gelen asalet. Sadece parmak baskısı (Acupressure) ile yapılan, germe içermeyen saygın bir terapi. (Nuad Rajasamnak)",
        "benefit": "Ruhsal dinginlik ve derin kas rahatlaması.",
        "usage": "Yasemin Yağı ile • Germe Yoktur"
    },
    {
        "id": "thai-toksen",
        "name": "Tok Sen (Hammer) Massage",
        "cat": "massage-thai",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "EXOTIC",
        "desc": "Kuzey Tayland'ın kadim titreşim terapisi. Ahşap tokmaklarla enerji hatlarına ritmik vuruşlar yapılır. Titreşimler kasların en derinine ulaşır.",
        "benefit": "Derin kas blokajlarını çözer (Deep Tissue).",
        "usage": "Plai Yağı (Ağrı Kesici) ile"
    },
    {
        "id": "thai-herbal",
        "name": "Thai Herbal Compress",
        "cat": "massage-thai",
        "price": "Bilgi Al",
        "img": "santis_card_thai_v1.png",
        "badge": "HEALING",
        "desc": "Buharda ısıtılmış 15 çeşit şifalı bitki kesesi (Zerdeçal, Limon Otu) ile yapılan sıcak terapi. Isı ve aroma, kasları gevşetir.",
        "benefit": "Kas ağrılarını dindirir ve enerji verir.",
        "usage": "Sıcak Kese Hediyesi ile"
    },
    {
        "id": "thai-golden",
        "name": "The Golden Triangle Ritual",
        "cat": "massage-thai",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "RITUAL",
        "desc": "120 dakikalık kutsal bir seremonisi. Sauna -> Hamam (Kese/Köpük) -> Relax Room -> Odaya Transfer (Thai Masajı + Sıcak Kese).",
        "benefit": "Tam kapsamlı, 4 aşamalı arınma yolculuğu.",
        "usage": "Toplam 120 Dk • Full Spa Deneyimi"
    },
    // SANTIS AYURVEDIC COLLECTION (Kerala Origins)
    {
        "id": "ayur-abhyanga",
        "name": "Abhyanga (The Anointing)",
        "cat": "massage-ayur",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "WARM OIL",
        "desc": "Kerala geleneğinde 'kutsanma' ritüeli. Vücut sıcaklığındaki (38°C) bol bitkisel yağ, 7 farklı pozisyonda ritmik hareketlerle uygulanır.",
        "benefit": "Lenfatik dolaşımı açar, cildi derinlemesine besler.",
        "usage": "Dosha'nıza özel ılık yağ ile (Vata/Pitta/Kapha)"
    },
    {
        "id": "ayur-shiro",
        "name": "Shirodhara (Mind Flow)",
        "cat": "massage-ayur",
        "price": "Bilgi Al",
        "img": "santis_card_shirodhara_v1.png",
        "badge": "3RD EYE",
        "desc": "Zihni susturan 'İlahi Akış'. Alnınızdaki 3. Göz noktasına ılık susam yağının, sarkaç hareketiyle (Oscillation) ritmik olarak akıtılmasıdır.",
        "benefit": "Uykusuzluk, stres ve anksiyete için en güçlü terapi.",
        "usage": "Susam Yağı & Sessizlik Protokolü"
    },
    {
        "id": "ayur-marma",
        "name": "Marma Therapy (Prana)",
        "cat": "massage-ayur",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "ENERGY",
        "desc": "İğnesiz akupunktur. Vücuttaki 107 hayati enerji noktasına (Marma) yapılan hassas dokunuşlarla yaşam enerjisi (Prana) blokajları açılır.",
        "benefit": "Kronik yorgunluğu siler, enerji akışını dengeler.",
        "usage": "Nefes teknikleri eşliğinde"
    },
    {
        "id": "ayur-vedic",
        "name": "The Vedic Journey",
        "cat": "massage-ayur",
        "price": "Bilgi Al",
        "img": "santis_card_shirodhara_v1.png",
        "badge": "SIGNATURE",
        "desc": "Beden ve Zihin dengesi için tam kapsamlı ritüel. Abhyanga (Sıcak Yağ Masajı) ile başlar, Shirodhara (Zihin Akışı) ile son bulur.",
        "benefit": "Bedensel gevşeme ve zihinsel berraklık.",
        "usage": "90 Dk • sound Healing Başlangıcı ile"
    },
    // SANTIS BALINESE COLLECTION (Island of the Gods)
    {
        "id": "bali-trad",
        "name": "Traditional Balinese (Pijat)",
        "cat": "massage-bali",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "DEEP TISSUE",
        "desc": "Bin yıllık şifa mirası. 'Skin Rolling' tekniği ile kas ve fasya yapışıklıkları açılır, enerji akışı sağlanır.",
        "benefit": "Derin doku gevşemesi ve kan dolaşımı artışı.",
        "usage": "Frangipani (Kamboja) Yağı ile"
    },
    {
        "id": "bali-lulur",
        "name": "Royal Lulur Ritual",
        "cat": "massage-bali",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "GOLDEN GLOW",
        "desc": "Java prenseslerinin düğün öncesi güzellik sırrı. Zerdeçal ve Pirinç özlü 'Lulur' peelingi sonrası Yasemin yağı ile parlatma (Dry Protocol).",
        "benefit": "Pürüzsüz, yumuşak ve altın ışıltılı bir cilt.",
        "usage": "Ayak Ritüeli + Scrub + Aroma Masaj"
    },
    {
        "id": "bali-boreh",
        "name": "Boreh Spice Remedy",
        "cat": "massage-bali",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "DEEP HEAT",
        "desc": "Bali çiftçilerinin 'Şifalı Isı' kürü. Zencefil, Karanfil ve Tarçın maskesi ile sırt ve omuzlardaki derin ağrılar dindirilir.",
        "benefit": "Romatizma, kas tutulması ve soğuk algınlığına doğal çözüm.",
        "usage": "Sıcak Maske + Baş Masajı"
    },
    {
        "id": "bali-foot",
        "name": "Balinese Foot Ritual",
        "cat": "massage-bali",
        "price": "Bilgi Al",
        "img": "santis_card_reflexology_v1.png",
        "badge": "REFLEXOLOGY",
        "desc": "Tapınak öncesi arınma ritüeli. Limon otlu suda yıkama ve Bambu çubuğu ile yapılan derin refleksoloji masajı.",
        "benefit": "Yorgun ayakları canlandırır, vücut enerjisini dengeler.",
        "usage": "30 Dk veya 50 Dk Seçeneği"
    },
    // SANTIS DETOX & ANTI-AGING (Clinical & Marine)
    {
        "id": "detox-vodder",
        "name": "Vodder Manual Lymph Drainage",
        "cat": "massage-detox",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "CLINICAL",
        "desc": "1930 Dr. Vodder klinik metodu. Tüy hafifliğinde 'Pumping' hareketleriyle ödem ve toksinlerin lenf kanallarına atılmasını sağlar.",
        "benefit": "Anında hafifleme, ödem atma, cerrahi sonrası iyileşme.",
        "usage": "Dry Brushing + 50 Dk Manuel Drenaj"
    },
    {
        "id": "detox-thalasso",
        "name": "Thalasso Slimming Hamam",
        "cat": "massage-detox",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "SIGNATURE",
        "desc": "Türk Hamamı ve Fransız Okyanus gücünün birleşimi. Kese ve köpükle açılan gözeneklere, sıcak 'Mikronize Yosun' (Algae) maskesi uygulanır.",
        "benefit": "Toksin atımı, sıkılaşma ve mineral yüklemesi.",
        "usage": "Kese/Köpük + Yosun Sargılama"
    },
    {
        "id": "detox-collagen",
        "name": "Collagen Hyaluronic Lift",
        "cat": "massage-detox",
        "price": "Bilgi Al",
        "img": "santis_card_products_v1.png",
        "badge": "NON-INVASIVE",
        "desc": "İğnesiz dolgu etkisi. Sothys 'Digiesthetique' parmak masajı tekniği ile Hyaluronik Asit ve Kolajen cildin derinlerine indirilir.",
        "benefit": "Tek seansta lifting ve dolgunlaşma (Plumping).",
        "usage": "75 Dk • Yüz ve Dekolte"
    },
    // --- NEW: ANTI-CELLULITE RESEARCH ADDITIONS ---
    {
        "id": "detox-g5",
        "name": "G5 Vibro-Sculpting",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_deeptissue_v1.png",
        "badge": "MECHANICAL",
        "desc": "İnatçı selülitler için mekanik çözüm. Hızlı titreşimli başlık (G5) ile yağ blokları parçalanır ve kan dolaşımı maksimum seviyeye çıkarılır.",
        "benefit": "Selülit görünümünü azaltır, dokuyu pürüzsüzleştirir.",
        "usage": "Bölgesel Uygulama (Bacak/Basen)"
    },
    {
        "id": "detox-madero",
        "name": "Brazilian Maderotherapy",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "WOOD",
        "desc": "Kolombiya menşeli 'Ahşap Terapisi'. Anatomik şekilli tahta silindirlerle yapılan ritmik masaj, lenfatik sistemi uyarır ve vücudu şekillendirir.",
        "benefit": "Vücut kontürünü belirginleştirir (Body Contouring).",
        "usage": "%100 Doğal Ahşap Ekipmanlar"
    },
    {
        "id": "detox-coffee",
        "name": "Espresso Slimming Ritual",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "CAFFEINE",
        "desc": "Kafeinin lipolitik (yağ yakıcı) gücü. Yeşil kahve çekirdekleri ve acı biber özlü maske, metabolizmayı hızlandırarak incelmeyi destekler.",
        "benefit": "Metabolik hızlanma ve sıkılaşma.",
        "usage": "Peeling + Maske + Masaj"
    },
    {
        "id": "detox-cryo",
        "name": "Cryo-Toning Bandage",
        "cat": "massage-anticellulite",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "COLD",
        "desc": "Soğuk etkisiyle şok sıkılaşma. Mentol ve kofur içerikli soğuk bandajlar, vücut ısısını düşürerek kalorinin ısı üretimi için harcanmasını sağlar.",
        "benefit": "Ödem atar, bacakları hafifletir.",
        "usage": "20 Dk Bandaj Sarımı"
    },
    // SANTIS WESTERN CLINICAL (Science of Wellness)
    {
        "id": "west-magnesium",
        "name": "Magnesium Muscle Melt",
        "cat": "massage-clinical",
        "price": "Bilgi Al",
        "img": "santis_card_deeptissue_v1.png",
        "badge": "RECOVERY",
        "desc": "Sporcular ve kronik ağrılar için biyolojik onarım. Hollanda 'Zechstein' denizinden saf Magnezyum Yağı ile kasların enerji (ATP) depoları şarj edilir.",
        "benefit": "Kramp, tutulma ve yorgunluğu 20 dakikada siler.",
        "usage": "Transdermal İnfüzyon (Yıkanmaz)"
    },
    {
        "id": "west-fireice",
        "name": "Fire & Ice Stone Therapy",
        "cat": "massage-clinical",
        "price": "Bilgi Al",
        "img": "santis_card_hammam_v1.png",
        "badge": "CONTRAST",
        "desc": "Damar jimnastiği. 55°C Volkanik Bazalt ve 0°C Soğuk Mermer taşlarının zıt etkisiyle dolaşım pompalanır. Vücut ısınırken zihin uyanır.",
        "benefit": "Enflamasyonu (yangıyı) dağıtır, canlılık verir.",
        "usage": "Sıcak & Soğuk Taş Kombinasyonu"
    },
    {
        "id": "west-sleep",
        "name": "The Deep Sleep Ritual",
        "cat": "massage-clinical",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "INSOMNIA",
        "desc": "Uykusuzluk için nöro-bilimsel çözüm. Vetiver ve Papatya yağları eşliğinde, Vagus sinirini uyaran hipnotik ve yavaş dokunuşlar.",
        "benefit": "Beyin dalgalarını yavaşlatır, deliksiz uyku sağlar.",
        "usage": "90 Dk • Sessizlik Protokolü"
    },
    {
        "id": "west-fascia",
        "name": "Myofascial Structural Release",
        "cat": "massage-clinical",
        "price": "Bilgi Al",
        "img": "santis_card_massage_v1.png",
        "badge": "POSTURE",
        "desc": "Ofis çalışanları (Tech-Neck) için yapısal düzeltme. Yağsız uygulanan bu teknikte, kası saran zar (Fasya) esnetilerek duruş bozuklukları giderilir.",
        "benefit": "Duruşu düzeltir, hareket kapasitesini artırır.",
        "usage": "Yağsız / Kuru Uygulama"
    }
];


function getCatName(cat) {
    const map = {
        'face-youth': 'Yüz / Gençlik', 'face-hydra': 'Yüz / Nem', 'face-detox': 'Yüz / Detox',
        'face-men': 'Erkek Bakımı', 'body-slim': 'Vücut / İncelme', 'body-care': 'Vücut Bakımı',
        'sun-care': 'Güneş Serisi', 'organics': 'Organik Seri', 'home-textile': 'Santis Home',
        'home-aroma': 'Aromaterapi', 'home-gift': 'Hediye',
        'campaign': '🔥 Fırsat Köşesi', 'accessory': 'Aksesuar & Yan Ürünler',
        // Massage Maps
        'massage-classic': 'Klasik Masajlar', 'massage-thai': 'Thai Terapileri',
        'massage-bali': 'Bali Masajları', 'massage-ayur': 'Ayurveda',
        'massage-detox': 'Detox & Sıkılaşma', 'massage-clinical': 'Klinik Terapi'
    };

    return map[cat] || 'Koleksiyon';
}

// --- DATA BRIDGE (Compat for Category Engine) ---
(function () {
    if (!window.productCatalog) return;

    // DEFENSIVE PATHING ENGINE
    // Detects if we are in a subfolder and adjusts path accordingly
    const getRoot = () => {
        // Method 1: Trust available global
        if (window.SITE_ROOT) return window.SITE_ROOT;
        if (window.SANTIS_ROOT) return window.SANTIS_ROOT;

        // Method 2: Auto-detect depth based on URL structure
        // /index.html -> depth 0
        // /tr/masajlar/index.html -> depth 2
        const path = window.location.pathname;
        // Count slashes, ignore empty start/end
        // Standardize: remove standard proto/domain if absolute
        // Simple heuristic: count segments after root
        // This is heuristic-based safe fallback
        if (path.includes('/tr/') || path.includes('/en/') || path.includes('/de/') || path.includes('/fr/') || path.includes('/ru/')) {
            if (path.split('/').length > 3) return "../../"; // tr/category/
        }
        return ""; // Root default
    };

    const ROOT = getRoot();
    // Ensure we don't double-slash or miss slash
    const BASE_IMG_PATH = ROOT + (ROOT.endsWith('/') ? "" : "/") + "assets/img/cards/";

    function mapProduct(p) {
        // Cleanse existing path if it accidentally has assets/ already
        let cleanImg = p.img.replace(/^(assets\/img\/cards\/|\.\.\/assets\/img\/cards\/)/, "");

        return {
            id: p.id,
            title: p.name,
            desc: p.desc,
            img: BASE_IMG_PATH + cleanImg,
            price: p.price,
            tier: p.badge || 'SANTIS',
            category: p.cat,
            slug: p.slug // Optional if exists
        };
    }

    // 1. MASSAGES (All Massage Types)
    window.SANTIS_MASSAGES = window.productCatalog.filter(p =>
        p.cat.startsWith('massage-') || p.id === 'thai-royal'
    ).map(mapProduct);

    // 2. HAMMAM (Body Care)
    window.SANTIS_HAMMAM = window.productCatalog.filter(p =>
        p.cat === 'body-care' || p.cat.includes('soap')
    ).map(mapProduct);

    // 3. SKINCARE (Face)
    window.SANTIS_SKINCARE = window.productCatalog.filter(p =>
        p.cat.startsWith('face-')
    ).map(mapProduct);

    // 4. PRODUCTS (All Items for Shop)
    window.SANTIS_PRODUCTS = window.productCatalog.map(p => {
        let mapped = mapProduct(p);
        mapped.tier = p.badge || 'SHOP'; // Override for shop context if needed
        return mapped;
    });

    // --- METADATA (For Grouped Display) ---
    window.SANTIS_MASSAGES_CATEGORY_LABELS = {
        'massage-classic': 'KLASİK MASAJLAR',
        'massage-thai': 'PRESTIGE THAI',
        'massage-bali': 'BALI & ENDONEZYA',
        'massage-ayur': 'HİNT AYURVEDA',
        'massage-clinical': 'KLİNİK & SPOR',
        'massage-anticellulite': 'VÜCUT ŞEKİLLENDİRME',
        'massage-detox': 'DETOX & SIKILAŞMA'
    };

    window.SANTIS_PRODUCTS_CATEGORY_LABELS = {
        'face-youth': 'YÜZ / GENÇLİK',
        'face-hydra': 'YÜZ / NEM',
        'face-men': 'ERKEK BAKIMI',
        'home-textile': 'SANTIS HOME',
        'home-aroma': 'AROMATERAPİ',
        'sun-care': 'GÜNEŞ SERİSİ'
    };

    window.SANTIS_PRODUCTS_CATEGORY_ORDER = [
        'face-youth', 'face-hydra', 'home-textile', 'home-aroma', 'sun-care', 'face-men'
    ];

    window.SANTIS_MASSAGES_CATEGORY_ORDER = [
        'massage-classic',
        'massage-thai',
        'massage-bali',
        'massage-ayur',
        'massage-clinical',
        'massage-detox'
    ];

    // Signal Ready
    window.SANTIS_DATA_READY = true;
    if (window.onNvDataReady) window.onNvDataReady();

    console.log("✅ Data Bridge: Connected to Category Engine.", {
        Massages: testCount(window.SANTIS_MASSAGES),
        Skin: testCount(window.SANTIS_SKINCARE),
        Products: testCount(window.SANTIS_PRODUCTS)
    });

    function testCount(arr) { return arr ? arr.length : 0; }
})();
