
import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime
import sentinel_analytics

REPORT_DIR = "reports"

class SentinelPDF:

    @staticmethod
    def generate_report(filename="Santis_Health_Report.pdf"):
        path = os.path.join(REPORT_DIR, filename)
        c = canvas.Canvas(path, pagesize=A4)
        width, height = A4
        
        # Data
        stats = sentinel_analytics.SentinelAnalytics.get_summary()
        
        # Colors
        GOLD = colors.HexColor("#D4AF37")
        DARK = colors.HexColor("#1A1A1A")
        GRAY = colors.HexColor("#666666")
        
        # BACKGROUND
        c.setFillColor(DARK)
        c.rect(0, 0, width, height, fill=True)
        
        # HEADER
        c.setFillColor(GOLD)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 80, "SANTIS SENTINEL")
        
        c.setFillColor(colors.white)
        c.setFont("Helvetica", 14)
        c.drawString(50, height - 105, "Autonomous Health Report")
        
        c.setFont("Helvetica", 10)
        c.setFillColor(GRAY)
        c.drawString(50, height - 125, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        # METRICS GRID
        y = height - 200
        x = 50
        
        def draw_metric(label, value, x_pos, y_pos):
            c.setFillColor(colors.HexColor("#333333"))
            c.roundRect(x_pos, y_pos, 120, 80, 8, fill=True, stroke=False)
            
            c.setFillColor(GOLD)
            c.setFont("Helvetica-Bold", 20)
            c.drawCentredString(x_pos + 60, y_pos + 40, str(value))
            
            c.setFillColor(colors.white)
            c.setFont("Helvetica", 10)
            c.drawCentredString(x_pos + 60, y_pos + 20, label)

        draw_metric("Stability Score", f"{stats['stability_score']}/100", 50, y)
        draw_metric("Current Audit", f"{stats['current_audit_score']}", 190, y)
        draw_metric("Total Incidents", f"{stats['total_incidents']}", 330, y)
        draw_metric("Auto-Fixed", f"{stats['fixed']}", 470, y)
        
        # INCIDENT SUMMARY
        y -= 50
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, y, "Incident Breakdown (Last 7 Days)")
        
        y -= 30
        c.setFont("Helvetica", 12)
        c.setFillColor(GRAY)
        
        for comp, count in stats['top_components'].items():
            if comp == "UNKNOWN": continue
            c.drawString(50, y, f"• {comp}: {count} incidents")
            y -= 20
            
        # FOOTER
        c.setFillColor(GRAY)
        c.setFont("Helvetica", 9)
        c.drawCentredString(width/2, 30, "Generated by Santis Autonomous Sentinel v3.0")
        
        c.save()
        return path

if __name__ == "__main__":
    print(SentinelPDF.generate_report())
