"""Add UserConsent and EncryptedStrings

Revision ID: 144014ea3874
Revises: 63dc59e225d7
Create Date: 2026-02-23 20:31:38.768050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144014ea3874'
down_revision: Union[str, Sequence[str], None] = '63dc59e225d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('MARKETING_EMAIL', 'MARKETING_SMS', 'DATA_PROCESSING', 'CROSS_BORDER_TRANSFER', name='consenttype'), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_customer_id'), 'user_consents', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_consents_customer_id'), table_name='user_consents')
    op.drop_table('user_consents')
    # ### end Alembic commands ###
