"""Add ai_persona_summary to customers

Revision ID: 63dc59e225d7
Revises: a348ed53f1b9
Create Date: 2026-02-23 20:17:58.541212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63dc59e225d7'
down_revision: Union[str, Sequence[str], None] = 'a348ed53f1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('ai_persona_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'ai_persona_summary')
    # ### end Alembic commands ###
