"""Add dynamic pricing columns to Service

Revision ID: 90447bb8a440
Revises: 144014ea3874
Create Date: 2026-02-23 20:41:50.535977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90447bb8a440'
down_revision: Union[str, Sequence[str], None] = '144014ea3874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('current_price_eur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('services', sa.Column('min_price_eur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('services', sa.Column('max_price_eur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('services', sa.Column('demand_multiplier', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'demand_multiplier')
    op.drop_column('services', 'max_price_eur')
    op.drop_column('services', 'min_price_eur')
    op.drop_column('services', 'current_price_eur')
    # ### end Alembic commands ###
