export const optimizerReasonCodes = {
  STRONG_REVENUE_GAIN: 'STRONG_REVENUE_GAIN',
  ABANDONMENT_REDUCTION: 'ABANDONMENT_REDUCTION',
  INTENT_RATE_GAIN: 'INTENT_RATE_GAIN',
  ASSIST_ACCEPTANCE_GAIN: 'ASSIST_ACCEPTANCE_GAIN',
  LOW_SAMPLE_SIZE: 'LOW_SAMPLE_SIZE',
  NO_CLEAR_WINNER: 'NO_CLEAR_WINNER',
  RISK_OF_OVERFITTING: 'RISK_OF_OVERFITTING',
} as const;

export const optimizerPolicyDefaults = {
  minimumSampleSize: 20,
  confidenceForAutoSuggestion: 0.7,
};
