// SANTIS CLUB - BLOG & NEWS DATABASE
// Generated by Control Center

const blogCatalog = [
    {
        id: 1,
        title: "Santis Club Yenilendi",
        date: "2024-01-15",
        category: "Duyuru",
        img: "blog-opening.jpg",
        summary: "Yenilenen yüzümüz ve genişleyen spa alanımızla hizmetinizdeyiz.",
        content: "Santis Club olarak misafirlerimize daha iyi hizmet verebilmek adına..."
    },
    {
        id: 2,
        title: "Kış Bakımı Önerileri",
        date: "2024-02-01",
        category: "İpucu",
        img: "blog-skincare.jpg",
        summary: "Soğuk havalarda cildinizi korumanın 5 altın kuralı.",
        content: "Kış aylarında kuruyan cildiniz için nemlendirici kullanımı çok önemlidir..."
    }
];
