import os
import sys
import shutil
import asyncio
from datetime import datetime

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

# Adjust path to find 'app' module
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db.session import engine, AsyncSessionLocal
from app.db.base import Base

# --- EXPLICIT MODEL IMPORTS (CRITICAL) ---
# Ensuring all models are registered in Base.metadata
from app.db.models.user import User
from app.db.models.tenant import Tenant
from app.db.models.revenue import DailyRevenue
from app.db.models.booking import Booking
from app.db.models.room import Room
from app.db.models.service import Service
from app.db.models.staff import Staff
from app.db.models.customer import Customer
from app.db.models.commission import StaffCommission

from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

DB_FILE = "santis.db"

async def rebuild():
    print("🛡️ SANTIS DATA DEFENSE PROTOCOL (vMega)")
    print("---------------------------------------")

    # 0️⃣ Phase 0: Risk Assessment
    env = os.getenv("ENVIRONMENT", "DEV")
    db_url = os.getenv("DATABASE_URL", "")
    
    is_prod_signal = env.upper() == "PROD" or "postgres" in db_url
    force_flag = "--force-prod" in sys.argv

    if is_prod_signal and not force_flag:
        print("🚨 CRITICAL: Production Environment Detected!")
        print("   To execute this destructive operation, use: python tools/rebuild_db_safe.py --force-prod")
        sys.exit(1)
        
    print(f"✅ Environment Check Passed: {env}")

    # 1️⃣ Phase 1: Connection Draining
    print("🔌 Draining DB Connections...")
    await engine.dispose()

    # 2️⃣ Phase 2: Atomic Backup
    if os.path.exists(DB_FILE):
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        backup_name = f"{DB_FILE}.bak_{timestamp}"
        try:
            shutil.copy(DB_FILE, backup_name)
            print(f"📦 Backup Secure: {backup_name}")
        except Exception as e:
            print(f"❌ Backup Failed: {e}")
            print("   Aborting to prevent data loss.")
            sys.exit(1)

    # 3️⃣ Phase 3: Surgical Reconstruction
    print("🏗️ Synchronizing Schema...")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)
    
    print("   -> Schema Validated.")

    # 4️⃣ Phase 4: Golden Record Seeding
    print("🌱 Seeding Golden Record...")
    async with AsyncSessionLocal() as session:
        async with session.begin():
            # 4.1 Tenant
            tenant = Tenant(
                name="Santis Club Main",
                # id=uuid.uuid4() # Auto-generated by model
            )
            session.add(tenant)
            await session.flush() # Populate ID

            # 4.2 Super Admin
            admin_password = os.getenv("SANTIS_ADMIN_PASSWORD", "Santis2026!")
            
            admin = User(
                email="admin@santis.com",
                hashed_password=pwd_context.hash(admin_password),
                is_active=True,
                is_superuser=True,
                is_platform_admin=True, 
                role="OWNER",
                tenant_id=tenant.id
            )
            session.add(admin)
        
        await session.commit()

    print("---------------------------------------")
    print("👑 SANTIS OS REBORN: Systems Nominal.")
    print("   Admin: admin@santis.com")
    print("   Pass : [ENV or Santis2026!]")
    print("---------------------------------------")

if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(rebuild())
